# Generated by Django 5.2.5 on 2025-09-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_role_user_is_buyer_user_is_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='size',
            new_name='length',
        ),
        migrations.AddField(
            model_name='property',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
