# Generated by Django 5.2.5 on 2025-09-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_property_address_property_city_property_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.AddField(
            model_name='property',
            name='county',
            field=models.CharField(default='India', max_length=50),
            preserve_default=False,
        ),
    ]
