# Generated by Django 5.2.5 on 2025-09-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_property_address_property_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='county',
            new_name='country',
        ),
    ]
