# Generated by Django 5.2.5 on 2025-09-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_property_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='viewers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
