# Generated by Django 5.2.5 on 2025-10-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_chatsession_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedsearch',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='property',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='seller',
        ),
        migrations.DeleteModel(
            name='PropertyTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='SavedSearch',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
