# Generated by Django 5.2.5 on 2025-10-02 13:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_enquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='visitrequest',
            name='scheduled_time',
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='alternative_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='alternative_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='confirmed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='confirmed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='preferred_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='preferred_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='seller_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='visitor_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='visitor_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='visitor_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='visitor_phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='app.property'),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
