# Generated by Django 5.2.5 on 2025-10-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_visitrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
